language: c
compiler: gcc
dist: trusty
sudo: false
services:
  - docker
addons:
  ssh_known_hosts:
  - marc0.fr:4242
  - 51.77.202.182:4242
before_install:
  - openssl aes-256-cbc -K $encrypted_2e847da1f6f4_key -iv $encrypted_2e847da1f6f4_iv
    -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/deploy_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
  - docker build -t zappy_server_tests .
script: docker run zappy_server_tests /bin/sh -c "cd /app/server; make tests_run"
deploy:
  - provider: script
    skip_cleanup: true
    script: ".travis/deploy.sh"
    on:
      branch: master
