##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Makefile
##

SRC			=	zappy_ai

NAME		=	../$(SRC)

all:	$(NAME)

$(NAME):
		cp $(SRC) $(NAME)

clean:
		@$(RM) $(NAME)

fclean:		clean

re:		fclean all

.PHONY:		all clean fclean re
