#!/usr/bin/env python3

import pygame

import argparse
import select
import socket
import re

def parse_options():
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("-p", "--port", type=int, action="store", dest="port", required=True, help="port is the port number")
    parser.add_argument("-h", "--machine", type=str, action="store", dest="machine", help="machine is the name of the machine; localhost by default", default="localhost")
    return parser.parse_args()

def recv():
    fds = select.select([sockfd], [], [], 0.1)
    if len(fds[0]) != 0 and fds[0][0] == sockfd:
        return sockfd.recv(1024).decode()
    else:
        return None

def send(message):
    message += '\n'
    sockfd.send(message.encode())

""" Connect client to GRAPHIC team """
def connect_client():
    sockfd.connect((args.machine, args.port))
    if recv() != "Welcome!\n":
        print("server should have responded 'Welcome\\n'")
        exit(1)
    send("GRAPHIC")

""" Return (width, height) """
def command_msz():
    send("msz")
    tmp = recv()
    return tuple(map(int, re.search(r"^msz ([1-9]\d*) ([1-9]\d*)$", tmp).groups()))

""" Return ["team_name", "team_name", ...] """
def command_tna():
    send("tna")
    teams = []
    for team in recv().split('\n'):
        tmp = re.search(r"^tna (\S+)$", team)
        if tmp == None:
            break
        token = tmp.groups()
        teams.append(token[0])
    return teams

def draw_text(text, x, y):
    label = myfont.render(text, 1, (255,255,0))
    window.blit(label, (x, y))

def draw_interface():
    pygame.draw.line(window, 0xFFFFFF, (400, 0), (400, 1080))
    draw_text(f"Width:  {width}", 100, 50)
    draw_text(f"Height: {height}", 100, 150)
    draw_text(f" Team Names:", 100, 250)
    teams = command_tna()
    i = 250
    for team in teams:
        draw_text(team, 280, i)
        i += 30

def draw_map():
    TILE_SIZE = (1080 - 20 - 20) / height
    for i in range(width):
        for j in range(height):
            x = i * TILE_SIZE + 1920 / 2 - width / 2 * TILE_SIZE
            y = j * TILE_SIZE + 1080 / 2 - height / 2 * TILE_SIZE
            pygame.draw.rect(window, 0x808080, pygame.Rect(x, y, TILE_SIZE, TILE_SIZE), 4)

def loop():
    tmp = recv()
    if tmp is None:
        return
    if tmp[-1] == '\n':
        tmp = tmp[:-1]
    input = tmp.split(' ')
    print('mdr', input)

def handle_event(event_list):
    for event in event_list:
        if event.type == pygame.QUIT or (event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE):
            exit(0)

args = parse_options()
sockfd = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
connect_client()
width, height = command_msz()

pygame.init()
window = pygame.display.set_mode((1920, 1080), pygame.FULLSCREEN)
myfont = pygame.font.SysFont("arial", 16)

draw_interface()
while True:
    handle_event(pygame.event.get())
    draw_map()
    loop()
    pygame.display.flip()
